kind: pipeline
name: default

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:current-alpine
    commands:
      - yarn command --scope "@servicecmd/cli" lint:check

  - name: build
    image: node:current-alpine
    commands:
      - yarn command --scope "@servicecmd/cli" build

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      git_method: gh
      add_modules:
        - semantic-release-monorepo
      override: npx --no-install lerna exec --scope "@servicecmd/cli" --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      npm_token:
        from_secret: npm_token
      update_readme: true
    when:
      branch:
        - master
      event:
        - push
