image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - transpile
  - publish

linting:
  stage: test
  script:
    - yarn --frozen-lockfile
    - yarn lint
  tags:
    - node

update_readme:
  stage: transpile
  script:
    - yarn --frozen-lockfile
    - yarn readme
  artifacts:
    paths:
      - README.md
    expire_in: 30 minutes
  tags:
    - node
  only:
    - tags
