name: semantic-release

on:
  push:
    branches: [develop, alpha, beta, rc]
  pull_request:
    branches: [develop, alpha, beta, rc]

jobs:
  semantic-release-mock:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        package: ["cli"]
    steps:
      - uses: actions/checkout@v2
      - name: Action For Semantic Release
        run:
          working-directory: packages/${{ matrix.package }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: cycjimmy/semantic-release-action@v2.3.0
        with:
          branches: |
            [
              'develop',
              {
                name: 'alpha',
                prerelease: true
              },
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'rc',
                prerelease: true
              }
            ]
          dry_run: true
      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "New release should be published: ${{ steps.semantic.outputs.new_release_version }}"
          echo "Major: ${{ steps.semantic.outputs.new_release_major_version }}"
          echo "Minor: ${{ steps.semantic.outputs.new_release_minor_version }}"
          echo "Patch: ${{ steps.semantic.outputs.new_release_patch_version }}"
